tee:
  secret-provisioner:
    web:
      hostname: ${IEXEC_SECRET_PROVISIONER_WEB_HOSTNAME:localhost}
      port: ${IEXEC_SECRET_PROVISIONER_WEB_PORT:8080}
    enclave:
      hostname: ${IEXEC_SECRET_PROVISIONER_ENCLAVE_HOSTNAME:localhost}
      port: ${IEXEC_SECRET_PROVISIONER_ENCLAVE_PORT:4433}

  worker:
    pipelines:
      - version: # v5
        pre-compute:
          image: # e.g.: iexechub/tee-worker-pre-compute:<version>-sconify-<scone-version>-production
          fingerprint:
          heap-size: # 3GB
          entrypoint: # /bin/bash /apploader.sh
        post-compute:
          image: # e.g.: iexechub/tee-worker-post-compute:<version>-sconify-<scone-version>-production
          fingerprint:
          heap-size: # 3GB
          entrypoint: # /bin/bash /apploader.sh

  gramine:
    sps:
      login: ${IEXEC_GRAMINE_SPS_WEB_LOGIN:admin}
      password: ${IEXEC_GRAMINE_SPS_WEB_PASSWORD:admin}
