FROM azul/zulu-openjdk-alpine:11.0.3-jre
#FROM iexechub/java-scone:11.0.3

COPY build/resources/main/entrypoint.sh entrypoint.sh
COPY build/resources/main/palaemonConfTemplateWithDataset.vm palaemonConfTemplateWithDataset.vm
COPY build/resources/main/palaemonConfTemplateWithoutDataset.vm palaemonConfTemplateWithoutDataset.vm

RUN chmod +x entrypoint.sh

COPY build/libs/iexec-sms-@projectversion@.jar iexec-sms.jar

ENV IEXEC_SMS_MONGO_HOST sms-mongo
ENV IEXEC_SMS_BLOCKCHAIN_NODE_ADDRESS http://chain:8545
ENV IEXEC_SCONE_CAS_HOST iexec-cas
ENV IEXEC_PALAEMON_CONFIG_FILE_WITH_DATASET palaemonConfTemplateWithDataset.vm
ENV IEXEC_PALAEMON_CONFIG_FILE_WITHOUT_DATASET palaemonConfTemplateWithoutDataset.vm

COPY src/main/resources/ssl-keystore-dev.p12 /ssl-keystore-dev.p12
ENV IEXEC_SMS_SSL_KEYSTORE /ssl-keystore-dev.p12

ENV IEXEC_SMS_STORAGE_ENCRYPTION_AES_KEY_PATH /scone/iexec-sms-aes.key

ENTRYPOINT ["./entrypoint.sh"]

# docker run -it -p 15000:15000 nexus.iex.ec/iexec-sms:0.0.1