#!/bin/bash

cd $(dirname $0)
BASE_DIR=$(pwd)

for i in "$@"
do
case $i in
    --new*)
    new=true
    shift
    ;;
esac
done

cd tee/sms

if [[ $new == true ]]; then
	echo "Creating new SMS ... "
	docker-compose down -v -t 0 > /dev/null 2>&1

  docker volume remove sms-scone-volume > /dev/null 2>&1
  docker volume create sms-scone-volume > /dev/null 2>&1

  # Fresh CAS & Post session
  PALAEMON_DIR=$BASE_DIR/../boot
  curl -k --cert $PALAEMON_DIR/conf/client.crt --key $PALAEMON_DIR/conf/client-key.key --data-binary @$PALAEMON_DIR/sms-palaemon-conf.yml -X POST https://localhost:18767/session
  echo
else
  echo "Keeping SMS files  ... "
  docker-compose down > /dev/null 2>&1
fi

gnome-terminal --tab --title="SMS" -- bash -c "docker-compose up; read line" #https://stackoverflow.com/a/3512861
WAIT=3m

echo "Starting SMS ...($WAIT)"
sleep $WAIT # required for Sconified SMS

cd $BASE_DIR
exit 0
